ARG BUILD_FROM='lsiobase/debian:bullseye'

FROM ${BUILD_FROM}
ARG DOWNLOAD_URL="https://github.com/hyperion-project/hyperion.ng/releases/download"
ARG BUILD_VERSION="2.0.16"

ENV LANG C.UTF-8
RUN apt-get update && apt-get install -y --no-install-recommends \
		libqt5widgets5 \
		libqt5serialport5 \
		libqt5sql5-sqlite \
		libqt5x11extras5 \
		libavahi-core7 \
		libavahi-compat-libdnssd1 \
		libusb-1.0-0 \
		libjpeg-dev \
		libssl1.1 \
		zlib1g \
		libcec6 \
		wget \
		v4l-utils \
	&& rm -rf /var/lib/apt/lists/*
COPY run.sh /
RUN chmod a+x /run.sh

RUN wget -q "${DOWNLOAD_URL}/${BUILD_VERSION}/Hyperion-${BUILD_VERSION}-Linux-amd64.tar.gz" -O - | tar -xvz -C /usr

VOLUME /config
EXPOSE 8090 8092 19333 19400 19444 19445
CMD [ "/run.sh" ]