services:

  mongo:
    image: mongo:4.4
    container_name: ns-mongo
    user: "${USER_NIGHTSCOUT}:${USER_DOCKER}"
    volumes:
      - ${APP_PATH}/mongo:/data/db
    networks:
      - ${NETWORK}
    restart: unless-stopped

  nightscout:
    image: 'nightscout/cgm-remote-monitor:latest'
    container_name: nightscout
    user: "${USER_NIGHTSCOUT}:${USER_DOCKER}"
    environment:
      API_SECRET: ${PASSWORD_NIGHTSCOUT}
      ALARM_HIGH: off
      ALARM_LOW: off
      ALARM_URGENT_HIGH: off
      ALARM_URGENT_LOW: off
      AUTH_DEFAULT_ROLES: denied
      BASAL_RENDER: default
      DISPLAY_UNITS: mmol/L
      ENABLE: ar2 basal bgi boluscalc bwp cage cob cors food iob openaps pump rawbg sage
      SHOW_PLUGINS: ar2 basal bgi boluscalc bwp cage cob food iob openaps pump rawbg sage
      INSECURE_USE_HTTP: 'true'
      NIGHT_MODE: on
      NODE_ENV: production
      PORT: 1337
      TZ: ${TZ}
      MONGO_CONNECTION: ${NIGHTSCOUT_MONGO_URI}
      DEVICESTATUS_ADVANCED: 'true'
      SHOW_FORECAST: openaps
      PUMP_FIELDS: reservoir clock
    depends_on:
      - mongo
    networks:
      - ${NETWORK}
    labels:
      caddy_0: ${GUI_URL_NIGHTSCOUT}
      caddy_0.reverse_proxy: "{{upstreams 1337}}"
      caddy_1: ${GUI_URL2_NIGHTSCOUT}
      caddy_1.redir: https://${GUI_URL_NIGHTSCOUT} permanent
    restart: unless-stopped

networks:
  caddy:
    external: true